PUT http://localhost:8080/checklists/1/checklistitems/1
Authorization: UnVpOnJ1aQ==
Content-Type: application/json

{
    "checklist_id": "1",
    "checklistitem_id": "1",
    "name": "Test PUT3",
    "description": "item test",
    "state": "completed"
}